/**
 * 18 U.S.C. § 3632(d)(4)(D) — convictions that make a prisoner ineligible to
 * earn FSA time credits. Verbatim from uscode.house.gov (text in effect on
 * September 25, 2026; fetched 2026-09-26), clause numbers as in the statute.
 * Generated from the fetched page — do not paraphrase.
 */
export const INELIGIBLE_OFFENSES: { clause: string; text: string }[] = [
  { clause: "i", text: "Section 32, relating to destruction of aircraft or aircraft facilities." },
  { clause: "ii", text: "Section 33, relating to destruction of motor vehicles or motor vehicle facilities." },
  { clause: "iii", text: "Section 36, relating to drive-by shootings." },
  { clause: "iv", text: "Section 81, relating to arson within special maritime and territorial jurisdiction." },
  { clause: "v", text: "Section 111(b), relating to assaulting, resisting, or impeding certain officers or employees using a deadly or dangerous weapon or inflicting bodily injury." },
  { clause: "vi", text: "Paragraph (1), (7), or (8) of section 113(a), relating to assault with intent to commit murder, assault resulting in substantial bodily injury to a spouse or intimate partner, a dating partner, or an individual who has not attained the age of 16 years, or assault of a spouse, intimate partner, or dating partner by strangling, suffocating, or attempting to strangle or suffocate." },
  { clause: "vii", text: "Section 115, relating to influencing, impeding, or retaliating against a Federal official by injuring a family member, except for a threat made in violation of that section." },
  { clause: "viii", text: "Section 116, relating to female genital mutilation." },
  { clause: "ix", text: "Section 117, relating to domestic assault by a habitual offender." },
  { clause: "x", text: "Any section of chapter 10, relating to biological weapons." },
  { clause: "xi", text: "Any section of chapter 11B, relating to chemical weapons." },
  { clause: "xii", text: "Section 351, relating to Congressional, Cabinet, and Supreme Court assassination, kidnapping, and assault." },
  { clause: "xiii", text: "Section 521, relating to criminal street gangs." },
  { clause: "xiv", text: "Section 751, relating to prisoners in custody of an institution or officer." },
  { clause: "xv", text: "Section 793, relating to gathering, transmitting, or losing defense information." },
  { clause: "xvi", text: "Section 794, relating to gathering or delivering defense information to aid a foreign government." },
  { clause: "xvii", text: "Any section of chapter 39, relating to explosives and other dangerous articles, except for section 836 (relating to the transportation of fireworks into a State prohibiting sale or use)." },
  { clause: "xviii", text: "Section 842(p), relating to distribution of information relating to explosives, destructive devices, and weapons of mass destruction, but only if the conviction involved a weapon of mass destruction (as defined in section 2332a(c))." },
  { clause: "xix", text: "Subsection (f)(3), (h), or (i) of section 844, relating to the use of fire or an explosive." },
  { clause: "xx", text: "Section 871, relating to threats against the President and successors to the Presidency." },
  { clause: "xxi", text: "Section 879, relating to threats against former Presidents and certain other persons." },
  { clause: "xxii", text: "Section 924(c), relating to unlawful possession or use of a firearm during and in relation to any crime of violence or drug trafficking crime." },
  { clause: "xxiii", text: "Section 1030(a)(1), relating to fraud and related activity in connection with computers." },
  { clause: "xxiv", text: "Section 1091, relating to genocide." },
  { clause: "xxv", text: "Any section of chapter 51, relating to homicide, except for section 1112 (relating to manslaughter), 1113 (relating to attempt to commit murder or manslaughter, but only if the conviction was for an attempt to commit manslaughter), 1115 (relating to misconduct or neglect of ship officers), or 1122 (relating to protection against the human immunodeficiency virus)." },
  { clause: "xxvi", text: "Any section of chapter 55, relating to kidnapping." },
  { clause: "xxvii", text: "Any offense under chapter 77, relating to peonage, slavery, and trafficking in persons, except for sections 1593 through 1596." },
  { clause: "xxviii", text: "Section 1751, relating to Presidential and Presidential staff assassination, kidnapping, and assault." },
  { clause: "xxix", text: "Section 1791, relating to providing or possessing contraband in prison." },
  { clause: "xxx", text: "Section 1792, relating to mutiny and riots." },
  { clause: "xxxi", text: "Section 1841(a)(2)(C), relating to intentionally killing or attempting to kill an unborn child." },
  { clause: "xxxii", text: "Section 1992, relating to terrorist attacks and other violence against railroad carriers and against mass transportation systems on land, on water, or through the air." },
  { clause: "xxxiii", text: "Section 2113(e), relating to bank robbery resulting in death." },
  { clause: "xxxiv", text: "Section 2118(c), relating to robberies and burglaries involving controlled substances resulting in assault, putting in jeopardy the life of any person by the use of a dangerous weapon or device, or death." },
  { clause: "xxxv", text: "Section 2119, relating to taking a motor vehicle (commonly referred to as \"carjacking\")." },
  { clause: "xxxvi", text: "Any section of chapter 105, relating to sabotage, except for section 2152." },
  { clause: "xxxvii", text: "Any section of chapter 109A, relating to sexual abuse." },
  { clause: "xxxviii", text: "Section 2250, relating to failure to register as a sex offender." },
  { clause: "xxxix", text: "Section 2251, relating to the sexual exploitation of children." },
  { clause: "xl", text: "Section 2251A, relating to the selling or buying of children." },
  { clause: "xli", text: "Section 2252, relating to certain activities relating to material involving the sexual exploitation of minors." },
  { clause: "xlii", text: "Section 2252A, relating to certain activities involving material constituting or containing child pornography." },
  { clause: "xliii", text: "Section 2260, relating to the production of sexually explicit depictions of a minor for importation into the United States." },
  { clause: "xliv", text: "Section 2283, relating to the transportation of explosive, biological, chemical, or radioactive or nuclear materials." },
  { clause: "xlv", text: "Section 2284, relating to the transportation of terrorists." },
  { clause: "xlvi", text: "Section 2291, relating to the destruction of a vessel or maritime facility, but only if the conduct that led to the conviction involved a substantial risk of death or serious bodily injury." },
  { clause: "xlvii", text: "Any section of chapter 113B, relating to terrorism." },
  { clause: "xlviii", text: "Section 2340A, relating to torture." },
  { clause: "xlix", text: "Section 2381, relating to treason." },
  { clause: "l", text: "Section 2442, relating to the recruitment or use of child soldiers." },
  { clause: "li", text: "An offense described in section 3559(c)(2)(F), for which the offender was sentenced to a term of imprisonment of more than 1 year, if the offender has a previous conviction, for which the offender served a term of imprisonment of more than 1 year, for a Federal or State offense, by whatever designation and wherever committed, consisting of murder (as described in section 1111), voluntary manslaughter (as described in section 1112), assault with intent to commit murder (as described in section 113(a)), aggravated sexual abuse and sexual abuse (as described in sections 2241 and 2242), abusive sexual contact (as described in sections 2244(a)(1) and (a)(2)), kidnapping (as described in chapter 55), carjacking (as described in section 2119), arson (as described in section 844(f)(3), (h), or (i)), or terrorism (as described in chapter 113B)." },
  { clause: "lii", text: "Section 57(b) of the Atomic Energy Act of 1954 (42 U.S.C. 2077(b)), relating to the engagement or participation in the development or production of special nuclear material." },
  { clause: "liii", text: "Section 92 of the Atomic Energy Act of 1954 (42 U.S.C. 2122), relating to prohibitions governing atomic weapons." },
  { clause: "liv", text: "Section 101 of the Atomic Energy Act of 1954 (42 U.S.C. 2131), relating to the atomic energy license requirement." },
  { clause: "lv", text: "Section 224 or 225 of the Atomic Energy Act of 1954 (42 U.S.C. 2274, 2275), relating to the communication or receipt of restricted data." },
  { clause: "lvi", text: "Section 236 of the Atomic Energy Act of 1954 (42 U.S.C. 2284), relating to the sabotage of nuclear facilities or fuel." },
  { clause: "lvii", text: "Section 60123(b) of title 49, relating to damaging or destroying a pipeline facility, but only if the conduct which led to the conviction involved a substantial risk of death or serious bodily injury." },
  { clause: "lviii", text: "Section 401(a) of the Controlled Substances Act (21 U.S.C. 841), relating to manufacturing or distributing a controlled substance in the case of a conviction for an offense described in subparagraph (A), (B), or (C) of subsection (b)(1) of that section for which death or serious bodily injury resulted from the use of such substance." },
  { clause: "lix", text: "Section 276(a) of the Immigration and Nationality Act (8 U.S.C. 1326), relating to the reentry of a removed alien, but only if the alien is described in paragraph (1) or (2) of subsection (b) of that section." },
  { clause: "lx", text: "Section 277 of the Immigration and Nationality Act (8 U.S.C. 1327), relating to aiding or assisting certain aliens to enter the United States." },
  { clause: "lxi", text: "Section 278 of the Immigration and Nationality Act (8 U.S.C. 1328), relating to the importation of an alien into the United States for an immoral purpose." },
  { clause: "lxii", text: "Any section of the Export Administration Act of 1979 (50 U.S.C. 4611 et seq.)" },
  { clause: "lxiii", text: "Section 206 of the International Emergency Economic Powers Act (50 U.S.C. 1705)." },
  { clause: "lxiv", text: "Section 601 of the National Security Act of 1947 (50 U.S.C. 3121), relating to the protection of identities of certain United States undercover intelligence officers, agents, informants, and sources." },
  { clause: "lxv", text: "Subparagraph (A)(i) or (B)(i) of section 401(b)(1) of the Controlled Substances Act (21 U.S.C. 841(b)(1)) or paragraph (1)(A) or (2)(A) of section 1010(b) of the Controlled Substances Import and Export Act (21 U.S.C. 960(b)), relating to manufacturing, distributing, dispensing, or possessing with intent to manufacture, distribute, dispense, or knowingly importing or exporting, a mixture or substance containing a detectable amount of heroin if the sentencing court finds that the offender was an organizer, leader, manager, or supervisor of others in the offense, as determined under the guidelines promulgated by the United States Sentencing Commission." },
  { clause: "lxvi", text: "Subparagraph (A)(vi) or (B)(vi) of section 401(b)(1) of the Controlled Substances Act (21 U.S.C. 841(b)(1)) or paragraph (1)(F) or (2)(F) of section 1010(b) of the Controlled Substances Import and Export Act (21 U.S.C. 960(b)), relating to manufacturing, distributing, dispensing, or possessing with intent to manufacture, distribute, or dispense, a mixture or substance containing a detectable amount of N-phenyl-N-[1-(2-phenylethyl)-4-piperidinyl] propanamide, or any analogue thereof." },
  { clause: "lxvii", text: "Subparagraph (A)(viii) or (B)(viii) of section 401(b)(1) of the Controlled Substances Act (21 U.S.C. 841(b)(1)) or paragraph (1)(H) or (2)(H) of section 1010(b) the Controlled Substances Import and Export Act (21 U.S.C. 960(b)), relating to manufacturing, distributing, dispensing, or possessing with intent to manufacture, distribute, or dispense, or knowingly importing or exporting, a mixture of substance containing a detectable amount of methamphetamine, its salts, isomers, or salts of its isomers, if the sentencing court finds that the offender was an organizer, leader, manager, or supervisor of others in the offense, as determined under the guidelines promulgated by the United States Sentencing Commission." },
  { clause: "lxviii", text: "Subparagraph (A) or (B) of section 401(b)(1) of the Controlled Substances Act (21 U.S.C. 841(b)(1)) or paragraph (1) or (2) of section 1010(b) of the Controlled Substances Import and Export Act (21 U.S.C. 960(b)), relating to manufacturing, distributing, dispensing, or possessing with intent to manufacture, distribute, or dispense, a controlled substance, or knowingly importing or exporting a controlled substance, if the sentencing court finds that- (I) the offense involved a mixture or substance containing a detectable amount of N-phenyl-N-[1-(2-phenylethyl)-4-piperidinyl] propanamide, or any analogue thereof; and (II) the offender was an organizer, leader, manager, or supervisor of others in the offense, as determined under the guidelines promulgated by the United States Sentencing Commission." },
];
